### ISSUE TITLE
Disable turn off AC

### ISSUE THREAD

**Issue by StGuLa** [oh2th/com.sensibo#36]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when [I turn off my AC by accident. It is so easy to do if you, are to fast, navigating in to adjust temp settings]

**Describe the solution you'd like**
Same as in vitual thermo app. 
The possibility to diasble shut off.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by oh2th** [comment]
No, the quick action in the Homey SDK and can not be changed.
