### ISSUE TITLE
Add "Accept-Encoding: gzip" to increase rate limit according to HTTP 429 rate limit response received

### ISSUE THREAD

**Issue by omere2** [oh2th/com.sensibo#38]
API Limit exceeded. Use "Accept-Encoding: gzip" to increase the rate limit.

**Comment by oh2th** [comment]
Thanks @omere2 for letting me know. Some users are already reporting this issue at the Homey Community also. Looks like node http.min doesn't support that so need to do some refactoring.

**Comment by oh2th** [comment]
Headers are set
    _header: 'GET /api/v2/pods/bQ9xT4Aa/acStates?limit=10&apiKey=XXXXXXXXXXXXXXXXXXXXXXXXX HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Accept-Encoding: gzip\r\n' +
      'User-Agent: axios/1.6.8\r\n' +
      'Host: home.sensibo.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
      
Still getting 429 rate limit
