### ISSUE TITLE
Error setting AC state (403 - Forbidden) , 429 

### ISSUE THREAD

**Issue by jorgenask86** [oh2th/com.sensibo#39]
**Describe the bug**
Cannot control AC with Sensibo Homey app. Get two different errors since afternoon 14th of April 2024
1. Error setting AC state (403 - Forbidden)
2. Error setting AC State (429 - Too many requests) .. Not 100% sure about the text here, but it was 429 for sure.

**App (please complete the following information):**
v1.17.5

**Desktop (please complete the following information):**
Homey Pro 2023

**Additional context**
Works fine on the Sensibo Android app, here I can controll the AC.
Also many others have the same issue at least here in Norway.
I also tried to make a new api key with https://home.sensibo.com/me/api , but did not make a difference.

**Comment by jerry86900** [comment]
Same issue. Also cannot add a device. 

![IMG_3722](https://github.com/oh2th/com.sensibo/assets/102232511/cb5e3e7a-c4ef-4a5f-886a-2d82dd2566fc)
![IMG_3706](https://github.com/oh2th/com.sensibo/assets/102232511/35d66782-1074-4edc-a7ed-2e511c1762f0)

**Comment by franry** [comment]
Same here

**Comment by oh2th** [comment]
Root cause is #39, will need refactoring of the code. Mean while increase your update interval.

**Comment by henninglensberg** [comment]
Same issue for me, but still same error avter setting update interval to 120

**Comment by Ronm10** [comment]
where can I find update interval on the device I only see polling interval

**Comment by jerry86900** [comment]
hey, thanks, but some of this has gone over my head and i cant get homey to control sensibo again. I have reinstalled the sensibo ap, and was able to re-add my devices, but still getting the 429 error. Ive set the update interval to 250, and now getting "Error setting AC state (403 - Forbidden)"

sorry, newby and baby steps appreciated.
